server:
  port: 8004

spring:
  application:
    name: springcloud-consul-provider
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}