server:
  port: 80

#不将feign注册到eureka注册中心了，因为它就是一个客户端
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


#设置feign客户端超时时间(OpenFeign默认支持ribbon),就是允许最大的连接延迟，下面设置的是5秒
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#开启feign客户端的日志
logging:
  level:
    # feign日志以什么级别监控哪个接口
    #设置需要打印那个接口的日志信息，后面的debug是设置打印日志的级别
    com.ywd.service.PaymentService: debug
