server:
  port: 80

spring:
  application:
    name: springcloud-consul-consumer
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}